seed: 42
do_train: True
do_predict: True 
do_ED_infer: True 

# top-level config #
paradigm: seq2seq
task_name: ED
dataset_name: ACE2005-EN
language: English
test_exists_labels: True

# file path # 
output_dir: output/ACE2005-EN
type2id_path: ./data/processed/ace2005-en/label2id.json
#train_file: ../../data/processed/ace2005-en/train.unified.jsonl
train_file: ./data/processed/ace2005-en/train.unified.jsonl
validation_file: data/processed/ace2005-en/valid.unified.jsonl
test_file: ./data/processed/ace2005-en/test.unified.jsonl

# config for data processor #
truncate_in_batch: True
return_token_type_ids: False 
truncate_seq2seq_output: True 

# model config #
model_type: t5
model_name_or_path: t5-base
hidden_size: 768
aggregation: none

# training config #
num_train_epochs: 10
max_seq_length: 160
max_out_length: 128
dataloader_num_workers: 2

generation_max_length: 128
generation_num_beams: 4
predict_with_generate: True 
ignore_pad_token_for_loss: True 

per_device_train_batch_size: 8
per_device_eval_batch_size: 16
gradient_accumulation_steps: 2
# eval_accumulation_steps: 4
learning_rate: 1.0e-4
weight_decay: 1.0e-5
warmup_ratio: 0.1 
max_grad_norm: 1
optim: adamw_torch

load_best_model_at_end: True
metric_for_best_model: micro_f1 
greater_is_better: True 

logging_strategy: steps
logging_steps: 100
evaluation_strategy: epoch
eval_steps: 500
save_strategy: epoch
save_steps: 500

# split inference #
split_infer: False 
split_infer_size: 500
